//! Contains an example hub implementation generated by the [hub] macro.

/// Example event handler trait.
pub trait EventHandler {
    /// An arbitrary signal.
    fn event(&mut self, input: i32) -> i32;
}

crate::hub! {
    ExampleHub {
        event1: dyn EventHandler,
        event2: dyn EventHandler,
    }
}
